---
- name: build 1.0
  hosts: db
  become: yes

  tasks:
  - name: Execute apt update in shell
    shell: apt update

  - name: Ensure maven package is present 
    apt: 
     name: maven
     state: present
     
  - name: Ensure default-jdk package is present
    apt: 
     name: default-jdk
     state: present
     
  - name: Ensure git package is present
    apt: 
     name: git
     state: present
     
  - name: Git clone boxfuse
    shell: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    args:
      chdir: /home
       
  - name: Run mvn package
    shell: mvn package
    args:
       chdir: /home/boxfuse-sample-java-war-hello
       
  - name: Fetch .war file's
    fetch:
     src: /home/boxfuse/boxfuse-sample-java-war-hello/target/hello-1.0.war
     dest: /home/hello-1.0.war
     
- name: Running .war on Tomcat
  hosts: web
  become: yes

  tasks:
  - name: Execute apt update in shell
    shell: apt update
  
  - name: Ensure Tomcat package is present 
    apt: 
     name: tomcat9
     state: present  
  - name: Copy .war files into Tomcat directory
    copy:
    src: /home/hello-1.0.war
    dest: /var/lib/tomcat9/webapps/hello-1.0.war
...