---
- name: nginx html
  hosts: db
  become: yes

  tasks:
  - name: Ensure nginx package is present 
    apt: 
     name: nginx
     state: present
  - lineinfile:
    path: /var/www/html/index.html
    state: absent
    regexp: '^Hello Nginx='
    replace: <p><script> document.write(new Date().toLocaleDateString()); </script></p>
