---
services:
    maven:
          build:
              context: ./
              dockerfile: Dockerfile2
          volumes:
              - volume1
    tomcat:
          build:
              context: ./
              dockerfile: Dockerfile3
          ports:
              - '8080:8080'
          volumes:
              - volume1
          depends_on:
              - maven
volumes:
    volume1: './home:/home'
...




