---
services:
    maven:
          build:
              context: ./
              dockerfile: Dockerfile2
          volumes:
              - 'volume1:/home/java'
    tomcat:
        image: dockertn3/tomcat-alpine-msfonts:latest
        ports:
              - '8080:8080'
        volumes:
              - 'volume1:/usr/local/tomcat/webapps'
        depends_on:
              - maven
    volumes:
         volume1: /home/java
...



