---
services:
    maven:
          build:
              context: ./
              dockerfile: Dockerfile2
          volumes:
              - './home:/home'
    tomcat:
        image: dockertn3/tomcat-alpine-msfonts:latest
        ports:
              - '8080:8080'
        volumes:
              - './boxfuse-sample-java-war-hello/target:/usr/local/tomcat/webapps'
        depends_on:
              - maven
...
