---
services:
    maven:
          build:
              context: ./home
              dockerfile: dockerfile2.Dockerfile
          volumes:
              - './home:/home'
    tomcat:
        image: lciclcazz/lca-tomcat:latest
        ports:
              - '8080:8080'
        volumes:
              - './home/boxfuse-sample-java-war-hello/target:/usr/local/tomcat/webapps'
        depends_on:
              - maven
...
